In [2]:
import numpy as np
list_ = [ '1' , '2' , '3', '4', '5' ]
array_list = np.array(object = list_)

In [5]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

#Ans: list_--> data type is list
#array_list--> data type is array

type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

In [9]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
for i in list_:
    print(i)

1
2
3
4
5


In [10]:
for i in array_list:
    print(i)

1
2
3
4
5


In [13]:
#Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
num_array.shape

(2, 3)

In [19]:
#(ii) size
num_array.size

6

In [24]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr1 = np.random.randint([[2,3] , [4,5]])
arr1

array([[0, 0],
       [2, 0]])

In [33]:
arr2=np.random.randint(0,10,(3,3))
arr2

array([[6, 0, 2],
       [9, 2, 5],
       [2, 9, 5]])